version: '3'

networks:
  app-tier:
    driver: bridge
services:
#  redis:
  #    image: "redis:alpine"
  #    ports:
  #      - "127.0.0.1:6379:6379"
  #    networks:
  #      - app-tier
  fb_test:
    build: .
    ports:
      - "8000:8000"
    command: ["python", "app.py"]